apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            server: nginx
    template:
        metadata:
            labels:
                server: nginx
        spec:
            containers:
            - name: nginx-fail
              image: nginx
              ports:
              - containerPort: 80
              volumeMounts:
              - name: volume-for-nginx-index
                mountPath: /usr/share/nginx/html
            volumes:
            - name: volume-for-nginx-index
              configMap:
                name: index-nginx