apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
        kubernetes.io/ingress.class: nginx
    name: my-ingress
    labels:
        server: nginx
spec:
    rules:
    - host: test.cluster.demo.wunder-it.tech
      http:
        paths:
        - path: /
          backend:
            serviceName: nginx-service
            servicePort: 80