apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: slowmo
spec:
    replicas: 1
    selector:
        matchLabels:
            server: slowmo
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 1
    template:
        metadata:
            labels:
                server: slowmo
        spec:
            containers:
            - name: slowmo
              image: raphaeldegail/slowmo:pi
              ports:
              - containerPort: 8080
              resources:
                  requests:
                      memory: "100Mi"
                      cpu: "100m"
                  limits:
                      memory: "300Mi"
                      cpu: "300m"